repos:
  # BUILT-IN HOOKS
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        name: Checking merge conflicts
      - id: detect-private-key
        name: Detecting private keys
      - id: no-commit-to-branch
        name: Preventing commits to main branch
        args: ['--branch', 'main']
  # VALIDATE-BRANCH-NAME
  - repo: local
    hooks:
      - id: validate-branch-name
        name: Validating Branch Name
        entry: pre-commit-hooks/validate-branch-name
        language: script
        stages: [pre-commit, post-checkout]
  # RUFF
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        name: Linting python code
        types: [python]
        args: ['--fix']
      - id: ruff-format
        name: Formatting python code
        types: [python]

  # ISORT
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sorting python imports

  # MYPY
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        types: [python]
        name: Type checking python code
        additional_dependencies:
          [django-stubs, djangorestframework-stubs]

  # BANDIT
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        name: Checking for python security issues

  # PRETTIER
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Formatting frontend code
        args:
          [
            '--tab-width',
            '2',
            '--single-quote',
            '--no-semi',
            'use-tabs',
            '--jsx-single-quote',
            '--print-width',
            '68',
          ]
